FROM caddy:2.11.4-builder-alpine AS builder
RUN xcaddy build v2.10.2 --with github.com/caddy-dns/mailinabox@v1.0.0

FROM caddy:2.11.4-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY caddy-entrypoint.sh /usr/local/bin/caddy-entrypoint
RUN chmod 755 /usr/local/bin/caddy-entrypoint
ENTRYPOINT ["/usr/local/bin/caddy-entrypoint"]
